# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://kAworu.github.io/octostrap3
title: Octostrap3 demo
subtitle: Twitter Bootstrap theme for Octopress
author: kAworu
# If you want to use duckduckgo as search engine
# use the following line for simple_search and set quack_search to true
# simple_search: https://www.duckduckgo.com/
simple_search: https://www.google.com/search
description: Simple demo blog for octostrap3

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "%a %e %b %Y, %l:%M %p"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /octostrap3/atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /octostrap3
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public/octostrap3
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
highlighter: pygments # default python pygments have been replaced by pygments.rb

paginate:  6          # Posts per page on the blog index
paginate_path: "blog/page/:num"  # Directory base for pagination URLs eg. /posts/2/
recent_posts: 4       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [
    asides/recent_posts.html,
    custom/asides/category_list.html
]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
blog_index_asides: [
    custom/asides/what_is_octostrap3.html,
    asides/recent_posts.html,
    custom/asides/category_list.html
]
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: kAworu
github_repo_count: 4
github_show_profile_link: true
github_skip_forks: true
github_skip_github_pages: false

# Twitter
twitter_user:
twitter_tweet_button: true

# Google +1
google_plus_one: true
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: octostrap3
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id:

# Facebook Like
facebook_like: true

# Duckduckgo as search engine
quack_search: false

# Yandex Metrika
yandex_metrika_tracking_id:
